version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    cooldown:
      default-days: 1
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      oxc:
        patterns:
          - "oxfmt"
          - "oxlint"
    ignore:
      - dependency-name: "@takeyaqa/pict-wasm"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 1
    commit-message:
      prefix: "ci"
      include: "scope"
