name: Publish to npm registry

on:
  release:
    types: [published]

env:
  PNPM_VERSION: 10
  NODE_VERSION: 22

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@26f6d4f2c533a43e6b5da0b4a5dd983f98f7b49a # v6.0.4
        with:
          version: ${{ env.PNPM_VERSION }}
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: Update npm to latest version
        run: npm install -g npm@latest
      - name: Install dependencies
        run: pnpm install
      - name: Publish to npm registry
        run: pnpm publish --no-git-checks
