name: Publish to npm registry

on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          ref: refs/tags/${{ github.event.release.tag_name }}
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          cache: true
      - uses: actions/setup-node@v7
        with:
          node-version-file: "package.json"
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: pnpm install
      - name: Publish to npm registry
        run: pnpm publish --no-git-checks
